/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mazegenerator;
import javax.swing.*;
import java.awt.*;
import java.util.Stack;

/**
 *
 * @author snyou
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    private Grid grid;
    
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mazePanel = new javax.swing.JPanel();
        widthLabel = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        widthField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        solveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mazePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mazePanelLayout = new javax.swing.GroupLayout(mazePanel);
        mazePanel.setLayout(mazePanelLayout);
        mazePanelLayout.setHorizontalGroup(
            mazePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mazePanelLayout.setVerticalGroup(
            mazePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        widthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        widthLabel.setText("Width:");

        generateButton.setText("Generate Maze");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        heightLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heightLabel.setText("Height:");

        solveButton.setText("Solve Maze");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mazePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(widthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(heightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(solveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(widthLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(heightLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generateButton)
                        .addComponent(solveButton)))
                .addGap(27, 27, 27)
                .addComponent(mazePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        try {
            int width = Integer.parseInt(widthField.getText());
            int height = Integer.parseInt(heightField.getText());
            grid = new Grid(width, height);
            MazeGenerator mazeGenerator = new MazeGenerator(grid);
            mazeGenerator.generateMaze(0, 0);
            
            Graphics g = mazePanel.getGraphics();
            mazePanel.paint(g); // Clear the panel
            drawMaze(g, grid, mazePanel.getWidth(), mazePanel.getHeight());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Positive integers only!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_generateButtonActionPerformed

    private void drawMaze(Graphics g, Grid grid, int panelWidth, int panelHeight) {
        int cellSize = Math.min(panelWidth / grid.width, panelHeight / grid.height); // Scale cells to fit the panel

        g.setColor(Color.GREEN);
        g.fillRect(1, 1, cellSize, cellSize);
        
        g.setColor(Color.RED);
        g.fillRect((grid.width - 1) * cellSize + 1, (grid.height - 1) * cellSize + 1, cellSize, cellSize);
        
        g.setColor(Color.BLACK);  // Set color for walls
        
        for (int x = 0; x < grid.width; x++) {
            for (int y = 0; y < grid.height; y++) {
                int topLeftX = x * cellSize;
                int topLeftY = y * cellSize;

                // Draw all four walls for each cell
                if (grid.getCell(x, y).getWalls()[0] == true) {
                    g.drawLine(topLeftX, topLeftY, topLeftX + cellSize, topLeftY); // Top wall
                }
                if (grid.getCell(x, y).getWalls()[1] == true) {
                    g.drawLine(topLeftX + cellSize, topLeftY, topLeftX + cellSize, topLeftY + cellSize); // Right wall
                }
                if (grid.getCell(x, y).getWalls()[2] == true) {
                    g.drawLine(topLeftX, topLeftY + cellSize, topLeftX + cellSize, topLeftY + cellSize); // Bottom wall
                }
                if (grid.getCell(x, y).getWalls()[3] == true) {
                    g.drawLine(topLeftX, topLeftY, topLeftX, topLeftY + cellSize); // Left wall
                }
            }
        }
    }
    
    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
        // TODO add your handling code here:
        try {

            MazeSolver mazeSolver = new MazeSolver(grid);
            Stack<Cell> solutionStack = mazeSolver.solveMaze(0, 0); // Store the result stack
                         
            Graphics g = mazePanel.getGraphics();
            drawSolution(g, grid, solutionStack, mazePanel.getWidth(), mazePanel.getHeight());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Generate a maze first!", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_solveButtonActionPerformed
    
    private void drawSolution(Graphics g, Grid grid, Stack<Cell> solutionStack, int panelWidth, int panelHeight) {
        int cellSize = Math.min(panelWidth / grid.width, panelHeight / grid.height); // Scale cells to fit the panel

        g.setColor(Color.BLUE);  // Set color for solution cells

        for (Cell cell : solutionStack) {
            int topLeftX = cell.getX() * cellSize + 1;
            int topLeftY = cell.getY() * cellSize + 1;
            g.fillRect(topLeftX, topLeftY, cellSize, cellSize); // Draw filled rectangle for each solution cell
        }
        
        g.setColor(Color.GREEN);
        g.fillRect(1, 1, cellSize, cellSize);
        
        g.setColor(Color.RED);
        g.fillRect((grid.width - 1) * cellSize + 1, (grid.height - 1) * cellSize + 1, cellSize, cellSize);

        g.setColor(Color.BLACK);  // Set color for walls
        for (int x = 0; x < grid.width; x++) {
            for (int y = 0; y < grid.height; y++) {
                int topLeftX = x * cellSize;
                int topLeftY = y * cellSize;

                // Draw all four walls for each cell
                if (grid.getCell(x, y).getWalls()[0] == true) {
                    g.drawLine(topLeftX, topLeftY, topLeftX + cellSize, topLeftY); // Top wall
                }
                if (grid.getCell(x, y).getWalls()[1] == true) {
                    g.drawLine(topLeftX + cellSize, topLeftY, topLeftX + cellSize, topLeftY + cellSize); // Right wall
                }
                if (grid.getCell(x, y).getWalls()[2] == true) {
                    g.drawLine(topLeftX, topLeftY + cellSize, topLeftX + cellSize, topLeftY + cellSize); // Bottom wall
                }
                if (grid.getCell(x, y).getWalls()[3] == true) {
                    g.drawLine(topLeftX, topLeftY, topLeftX, topLeftY + cellSize); // Left wall
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generateButton;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JPanel mazePanel;
    private javax.swing.JButton solveButton;
    private javax.swing.JTextField widthField;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
}
