/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;
import javax.swing.JOptionPane;

/**
 *
 * @author snyou
 */
public class DisplayEdit extends javax.swing.JFrame {
    
    private MyHashTable table;
    private Homepage homepageFrame;
    private EmployeeInfo refNum;
    private EditEmployeeSearch cancelFrame;

    /**
     * Creates new form temp
     */
    public DisplayEdit() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        table = refvalForHT;
    }
    
    public void setHomepage(Homepage refvalForHP) {
        homepageFrame = refvalForHP;
    }
    
    public void setCancel(EditEmployeeSearch refval) {
        cancelFrame = refval;
    }
    
    public void setRefVal(EmployeeInfo refvalforEmployee) {
        refNum = refvalforEmployee;
        
        EmployeeNumber.setText(String.valueOf(refNum.empNum));
        FirstName.setText(refNum.firstName);
        LastName.setText(refNum.lastName);
        if (refNum.gender.equals("Male")) {
            MaleButton.setSelected(true);
        }
        if (refNum.gender.equals("Female")) {
            FemaleButton.setSelected(true);
        }
        WorkLocation.setText(refNum.workLoc);
        DeductRate.setText(String.valueOf(refNum.deductRate));
        
        if (refNum instanceof PTE) {
            PTE partTime = (PTE) refNum;

            PTEButton.setSelected(true);
            
            HourlyWage_YearlySalaryLabel.setText("Hourly Wage");
            HourlyWage_YearlySalary.setText(String.valueOf(partTime.hourlyWage));
            HourlyWage_YearlySalaryLabel.setVisible(true);
            HourlyWage_YearlySalary.setVisible(true);
            
            HoursPerWeekLabel.setText("Hours Per Week");
            HoursPerWeek.setText(String.valueOf(partTime.hoursPerWeek));
            HoursPerWeekLabel.setVisible(true);
            HoursPerWeek.setVisible(true);
            
            WeeksPerYearLabel.setText("Weeks Per Year");
            WeeksPerYear.setText(String.valueOf(partTime.weeksPerYear));
            WeeksPerYearLabel.setVisible(true);
            WeeksPerYear.setVisible(true);
        }
        else if (refNum instanceof FTE) {
            FTE fullTime = (FTE) refNum;
            
            FTEButton.setSelected(true);
            
            HourlyWage_YearlySalaryLabel.setText("Yearly Salary");
            HourlyWage_YearlySalary.setText(String.valueOf(fullTime.yearlySalary));
            HourlyWage_YearlySalaryLabel.setVisible(true);
            HourlyWage_YearlySalary.setVisible(true);
            
            HoursPerWeekLabel.setVisible(false);
            HoursPerWeek.setVisible(false);
            
            WeeksPerYearLabel.setVisible(false);
            WeeksPerYear.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaleFemale = new javax.swing.ButtonGroup();
        FTEPTE = new javax.swing.ButtonGroup();
        Title = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastNameLable = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        WorkLocationLabel = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JTextField();
        DeductRateLabel = new javax.swing.JLabel();
        DeductRate = new javax.swing.JTextField();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        HourlyWage_YearlySalary = new javax.swing.JTextField();
        HoursPerWeekLabel = new javax.swing.JLabel();
        HoursPerWeek = new javax.swing.JTextField();
        WeeksPerYearLabel = new javax.swing.JLabel();
        FTEButton = new javax.swing.JRadioButton();
        PTEButton = new javax.swing.JRadioButton();
        EmployeeTypeLabel = new javax.swing.JLabel();
        HourlyWage_YearlySalaryLabel = new javax.swing.JLabel();
        WeeksPerYear = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Edit An Employee");

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");

        EmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First Name");

        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LastNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLable.setText("Last Name");

        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Gender");

        WorkLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkLocationLabel.setText("Work Location");

        WorkLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DeductRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeductRateLabel.setText("Deduct Rate");

        DeductRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaleFemale.add(MaleButton);
        MaleButton.setText("Male");

        MaleFemale.add(FemaleButton);
        FemaleButton.setText("Female");

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MaleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FemaleButton))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleButton)
                    .addComponent(FemaleButton))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        HourlyWage_YearlySalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        HoursPerWeekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        HoursPerWeek.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        WeeksPerYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        FTEPTE.add(FTEButton);
        FTEButton.setText("Full Time");
        FTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEButtonActionPerformed(evt);
            }
        });

        FTEPTE.add(PTEButton);
        PTEButton.setText("Part Time");
        PTEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEButtonActionPerformed(evt);
            }
        });

        EmployeeTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeTypeLabel.setText("Employee Type");

        HourlyWage_YearlySalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        WeeksPerYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FTEButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PTEButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HourlyWage_YearlySalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(HourlyWage_YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FTEButton)
                    .addComponent(PTEButton))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HourlyWage_YearlySalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HourlyWage_YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(WeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
            if (PTEButton.isSelected()) {                                       
                PTE pte = new PTE();
                pte.empNum = Integer.parseInt(EmployeeNumber.getText());
                if (table.getFromTable(pte.empNum) != null && pte.empNum != refNum.empNum) {
                    JOptionPane.showMessageDialog(null, "Employee with this employee number already exists!", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }             
                pte.firstName = FirstName.getText().strip();
                pte.lastName = LastName.getText().strip();
                if (MaleButton.isSelected()) {
                    pte.gender = "Male";
                }
                if (FemaleButton.isSelected()) {
                    pte.gender = "Female";
                }
                pte.workLoc = WorkLocation.getText().strip();
                pte.deductRate = Double.parseDouble(DeductRate.getText());
                pte.hourlyWage = Double.parseDouble(HourlyWage_YearlySalary.getText());
                pte.hoursPerWeek = Double.parseDouble(HoursPerWeek.getText());
                pte.weeksPerYear = Double.parseDouble(WeeksPerYear.getText());

                if (pte.firstName.equals("") || pte.lastName.equals("") || pte.workLoc.equals("")) {
                    JOptionPane.showMessageDialog(null, "Invalid employee input", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }         
                
                if (pte.deductRate < 0 || pte.deductRate > 1) {
                    JOptionPane.showMessageDialog(null, "Deduct rate must be between 0 and 1 (inclusive)", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (pte.hourlyWage < 0) {
                    JOptionPane.showMessageDialog(null, "Hourly wage must be greater than 0", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (pte.hoursPerWeek < 0 || pte.hoursPerWeek > 48) {
                    JOptionPane.showMessageDialog(null, "Hours per week must be between 0 and 48", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (pte.weeksPerYear < 0 || pte.weeksPerYear > 52) {
                    JOptionPane.showMessageDialog(null, "Weeks per year must be between 0 and 52", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }  
                table.removeFromTable(refNum.empNum);

                table.addToTable(pte);
                System.out.println("added PTE!");
            }
            else if (FTEButton.isSelected()) {                
                FTE fte = new FTE();
                fte.empNum = Integer.parseInt(EmployeeNumber.getText());
                if (table.getFromTable(fte.empNum) != null && fte.empNum != refNum.empNum) {
                    JOptionPane.showMessageDialog(null, "Employee with this employee number already exists!", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }   
                fte.firstName = FirstName.getText().strip();
                fte.lastName = LastName.getText().strip();
                if (MaleButton.isSelected()) {
                    fte.gender = "Male";
                }
                if (FemaleButton.isSelected()) {
                    fte.gender = "Female";
                }
                fte.workLoc = WorkLocation.getText().strip();
                fte.deductRate = Double.parseDouble(DeductRate.getText());
                fte.yearlySalary = Double.parseDouble(HourlyWage_YearlySalary.getText());

                if (fte.firstName.equals("") || fte.lastName.equals("") || fte.workLoc.equals("")) {
                    JOptionPane.showMessageDialog(null, "Invalid input", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (fte.deductRate < 0 || fte.deductRate > 1) {
                    JOptionPane.showMessageDialog(null, "Deduct rate must be between 0 and 1 (inclusive)", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                if (fte.yearlySalary < 0) {
                    JOptionPane.showMessageDialog(null, "Yearly salary must be greater than 0", "", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                table.removeFromTable(refNum.empNum);
                
                table.addToTable(fte);
                System.out.println("added FTE!");

            }
            homepageFrame.setVisible(true);
            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid input", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        cancelFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void FTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEButtonActionPerformed
        // TODO add your handling code here:
        HourlyWage_YearlySalaryLabel.setText("Yearly Salary");
        HourlyWage_YearlySalaryLabel.setVisible(true);
        HourlyWage_YearlySalary.setVisible(true);

        HoursPerWeekLabel.setVisible(false);
        HoursPerWeek.setVisible(false);

        WeeksPerYearLabel.setVisible(false);
        WeeksPerYear.setVisible(false);
        
        if (refNum instanceof PTE) {
            HourlyWage_YearlySalary.setText("");
            HoursPerWeek.setText("");
            WeeksPerYear.setText("");
        }
    }//GEN-LAST:event_FTEButtonActionPerformed

    private void PTEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEButtonActionPerformed
        // TODO add your handling code here:
        HourlyWage_YearlySalaryLabel.setText("Hourly Wage");
        HourlyWage_YearlySalaryLabel.setVisible(true);
        HourlyWage_YearlySalary.setVisible(true);

        HoursPerWeekLabel.setText("Hours Per Week");
        HoursPerWeekLabel.setVisible(true);
        HoursPerWeek.setVisible(true);

        WeeksPerYearLabel.setText("Weeks Per Year");
        WeeksPerYearLabel.setVisible(true);
        WeeksPerYear.setVisible(true);
        
        if (refNum instanceof FTE) {
            HourlyWage_YearlySalary.setText("");
        }
    }//GEN-LAST:event_PTEButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DeductRate;
    private javax.swing.JLabel DeductRateLabel;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JLabel EmployeeTypeLabel;
    private javax.swing.JRadioButton FTEButton;
    private javax.swing.ButtonGroup FTEPTE;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField HourlyWage_YearlySalary;
    private javax.swing.JLabel HourlyWage_YearlySalaryLabel;
    private javax.swing.JTextField HoursPerWeek;
    private javax.swing.JLabel HoursPerWeekLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.ButtonGroup MaleFemale;
    private javax.swing.JRadioButton PTEButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField WeeksPerYear;
    private javax.swing.JLabel WeeksPerYearLabel;
    private javax.swing.JTextField WorkLocation;
    private javax.swing.JLabel WorkLocationLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
