package com.mycompany.ems;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author snyou
 */
public class DisplayFTE extends javax.swing.JFrame {

    private Homepage homepageFrame;
    private EmployeeInfo refNum;
    /**
     * Creates new form DisplayFTE
     */
    public DisplayFTE() {
        initComponents();
    }
    
    public void setHomepage(Homepage refvalForHP) {
        homepageFrame = refvalForHP;
    }
    
    public void setRefVal(EmployeeInfo refvalforEmployee) {
        refNum = refvalforEmployee;
        
        FTE fullTime = (FTE) refNum;
        EmployeeNumber.setText(String.valueOf(refNum.empNum));
        FirstName.setText(refNum.firstName);
        LastName.setText(refNum.lastName);
        Gender.setText(refNum.gender);
        WorkLocation.setText(refNum.workLoc);
        DeductRate.setText(String.valueOf(refNum.deductRate));

        YearlySalary.setText(String.valueOf(fullTime.yearlySalary));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastNameLable = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        WorkLocationLabel = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JLabel();
        DeductRateLabel = new javax.swing.JLabel();
        DeductRate = new javax.swing.JLabel();
        YearlySalaryLabel = new javax.swing.JLabel();
        YearlySalary = new javax.swing.JLabel();
        HomepageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Search For An Employee");

        InputPanel.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");
        InputPanel.add(EmployeeNumberLabel);

        EmployeeNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(EmployeeNumber);

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First Name");
        InputPanel.add(FirstNameLabel);

        FirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(FirstName);

        LastNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLable.setText("Last Name");
        InputPanel.add(LastNameLable);

        LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(LastName);

        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Gender");
        InputPanel.add(GenderLabel);

        Gender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(Gender);

        WorkLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkLocationLabel.setText("Work Location");
        InputPanel.add(WorkLocationLabel);

        WorkLocation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(WorkLocation);

        DeductRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeductRateLabel.setText("Deduct Rate");
        InputPanel.add(DeductRateLabel);

        DeductRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(DeductRate);

        YearlySalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearlySalaryLabel.setText("Yearly Salary");
        InputPanel.add(YearlySalaryLabel);

        YearlySalary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InputPanel.add(YearlySalary);

        HomepageButton.setText("Homepage");
        HomepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomepageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HomepageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomepageButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomepageButtonActionPerformed
        // TODO add your handling code here:
        homepageFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_HomepageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayFTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayFTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeductRate;
    private javax.swing.JLabel DeductRateLabel;
    private javax.swing.JLabel EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JButton HomepageButton;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel WorkLocation;
    private javax.swing.JLabel WorkLocationLabel;
    private javax.swing.JLabel YearlySalary;
    private javax.swing.JLabel YearlySalaryLabel;
    // End of variables declaration//GEN-END:variables
}
