/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;
import javax.swing.JOptionPane;

/**
 *
 * @author snyou
 */
public class EditPTEEmployee extends javax.swing.JFrame {

    private MyHashTable table;
    private Homepage homepageFrame;
    private EmployeeInfo refNum;
    private EditEmployeeSearch cancelFrame;
    /**
     * Creates new form EditPTEEmployee
     */
    public EditPTEEmployee() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        table = refvalForHT;
    }    
    public void setHomepage(Homepage refvalForHP) {
        homepageFrame = refvalForHP;
    }
    
    public void setCancel(EditEmployeeSearch refval) {
        cancelFrame = refval;
    }
    
    public void setRefVal(EmployeeInfo refvalforEmployee) {
        refNum = refvalforEmployee;
        
        PTE partTime = (PTE) refNum;
        EmployeeNumber.setText(String.valueOf(refNum.empNum));
        FirstName.setText(refNum.firstName);
        LastName.setText(refNum.lastName);
        if (refNum.gender.equals("Male")) {
            MaleButton.setSelected(true);
        }
        if (refNum.gender.equals("Female")) {
            FemaleButton.setSelected(true);
        }
        WorkLocation.setText(refNum.workLoc);
        DeductRate.setText(String.valueOf(refNum.deductRate));

        HourlyWage.setText(String.valueOf(partTime.hourlyWage));
        HoursPerWeek.setText(String.valueOf(partTime.hoursPerWeek));
        WeeksPerYear.setText(String.valueOf(partTime.weeksPerYear));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MaleFemaleGroup = new javax.swing.ButtonGroup();
        SubmitCancelPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastNameLable = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        WorkLocationLabel = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JTextField();
        DeductRateLabel = new javax.swing.JLabel();
        DeductRate = new javax.swing.JTextField();
        HourlyWageLabel = new javax.swing.JLabel();
        HourlyWage = new javax.swing.JTextField();
        HoursPerWeekLabel = new javax.swing.JLabel();
        HoursPerWeek = new javax.swing.JTextField();
        WeeksPerYearLabel = new javax.swing.JLabel();
        WeeksPerYear = new javax.swing.JTextField();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitCancelPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(SubmitButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(CancelButton);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Edit An Employee");

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");

        EmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First Name");

        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LastNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLable.setText("Last Name");

        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Gender");

        WorkLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkLocationLabel.setText("Work Location");

        WorkLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DeductRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeductRateLabel.setText("Deduct Rate");

        DeductRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        HourlyWageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HourlyWageLabel.setText("Hourly Wage");

        HourlyWage.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        HoursPerWeekLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HoursPerWeekLabel.setText("Hours Per Week");

        HoursPerWeek.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        WeeksPerYearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WeeksPerYearLabel.setText("Weeks Per Year");

        WeeksPerYear.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaleFemaleGroup.add(MaleButton);
        MaleButton.setText("Male");

        MaleFemaleGroup.add(FemaleButton);
        FemaleButton.setText("Female");

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MaleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FemaleButton))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(HourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(HourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(HoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(HoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(WeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(WeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaleButton)
                    .addComponent(FemaleButton))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HourlyWageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HoursPerWeekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WeeksPerYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        try {
            PTE pte = new PTE();
            pte.empNum = Integer.parseInt(EmployeeNumber.getText());
            if (table.getFromTable(pte.empNum) != null) {
                JOptionPane.showMessageDialog(null, "Employee with this employee number already exists!", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }             pte.firstName = FirstName.getText();
            pte.lastName = LastName.getText();
            if (MaleButton.isSelected()) {
                pte.gender = "Male";
            }
            if (FemaleButton.isSelected()) {
                pte.gender = "Female";
            }
            pte.workLoc = WorkLocation.getText();
            pte.deductRate = Double.parseDouble(DeductRate.getText());
            pte.hourlyWage = Double.parseDouble(HourlyWage.getText());
            pte.hoursPerWeek = Double.parseDouble(HoursPerWeek.getText());
            pte.weeksPerYear = Double.parseDouble(WeeksPerYear.getText());

            table.addToTable(pte);

            homepageFrame.setVisible(true);
            System.out.println("added PTE!");

            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Employee Input", "", JOptionPane.INFORMATION_MESSAGE);
        }

    }                                            

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        cancelFrame.setVisible(true);

        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPTEEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPTEEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPTEEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPTEEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPTEEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DeductRate;
    private javax.swing.JLabel DeductRateLabel;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JTextField HourlyWage;
    private javax.swing.JLabel HourlyWageLabel;
    private javax.swing.JTextField HoursPerWeek;
    private javax.swing.JLabel HoursPerWeekLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.ButtonGroup MaleFemaleGroup;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitCancelPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField WeeksPerYear;
    private javax.swing.JLabel WeeksPerYearLabel;
    private javax.swing.JTextField WorkLocation;
    private javax.swing.JLabel WorkLocationLabel;
    // End of variables declaration                   
}
