/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;

/**
 *
 * @author snyou
 */
public class FTEInfo extends javax.swing.JFrame {

    /**
     * Creates new form FTEInfo
     */
    public FTEInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SubmitCancelPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastNameLable = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        WorkLocationLabel = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JTextField();
        DeductRateLabel = new javax.swing.JLabel();
        DeductRate = new javax.swing.JTextField();
        YearlySalaryLabel = new javax.swing.JLabel();
        YearlySalary = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitCancelPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(SubmitButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(CancelButton);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Full-Time Employee");

        InputPanel.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");
        InputPanel.add(EmployeeNumberLabel);

        EmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(EmployeeNumber);

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First Name");
        InputPanel.add(FirstNameLabel);

        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(FirstName);

        LastNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLable.setText("Last Name");
        InputPanel.add(LastNameLable);

        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(LastName);

        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Gender");
        InputPanel.add(GenderLabel);

        Gender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(Gender);

        WorkLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkLocationLabel.setText("Work Location");
        InputPanel.add(WorkLocationLabel);

        WorkLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(WorkLocation);

        DeductRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeductRateLabel.setText("Deduct Rate");
        InputPanel.add(DeductRateLabel);

        DeductRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(DeductRate);

        YearlySalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearlySalaryLabel.setText("Yearly Salary");
        InputPanel.add(YearlySalaryLabel);

        YearlySalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(YearlySalary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        FTE fte = new FTE();
        fte.empNum = Integer.parseInt(EmployeeNumber.getText());
        fte.firstName = FirstName.getText();
        fte.lastName = LastName.getText();
        fte.gender = Integer.parseInt(Gender.getText());
        fte.workLoc = WorkLocation.getText();
        fte.deductRate = Double.parseDouble(DeductRate.getText());
        fte.yearlySalary = Double.parseDouble(YearlySalary.getText());

        // table.addToTable(fte);
        
        Homepage homepageFrame = new Homepage();
        homepageFrame.setVisible(true);
        
        this.dispose();
    }                                            

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        Homepage homepageFrame = new Homepage();
        homepageFrame.setVisible(true);
        
        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTEInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DeductRate;
    private javax.swing.JLabel DeductRateLabel;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField Gender;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitCancelPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField WorkLocation;
    private javax.swing.JLabel WorkLocationLabel;
    private javax.swing.JTextField YearlySalary;
    private javax.swing.JLabel YearlySalaryLabel;
    // End of variables declaration                   
}
