/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author snyou
 */
public class FTEInfo extends javax.swing.JFrame {

    private MyHashTable table;
    private Homepage homepageFrame;
    private PTE_or_FTE cancelFrame;
    /**
     * Creates new form FTEInfo
     */
    public FTEInfo() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        table = refvalForHT;
    }
    
    public void setHomepage(Homepage refvalForHP) {
        homepageFrame = refvalForHP;
    }
    
    public void setCancel(PTE_or_FTE refVal) {
        cancelFrame = refVal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        MaleFemaleGroup = new javax.swing.ButtonGroup();
        SubmitCancelPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastNameLable = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        GenderLabel = new javax.swing.JLabel();
        WorkLocationLabel = new javax.swing.JLabel();
        WorkLocation = new javax.swing.JTextField();
        DeductRateLabel = new javax.swing.JLabel();
        DeductRate = new javax.swing.JTextField();
        YearlySalaryLabel = new javax.swing.JLabel();
        YearlySalary = new javax.swing.JTextField();
        FemaleButton = new javax.swing.JRadioButton();
        MaleButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SubmitCancelPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(SubmitButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(CancelButton);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Full-Time Employee");

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");

        EmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLabel.setText("First Name");

        FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        LastNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastNameLable.setText("Last Name");

        LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        GenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GenderLabel.setText("Gender");

        WorkLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WorkLocationLabel.setText("Work Location");

        WorkLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        DeductRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DeductRateLabel.setText("Deduct Rate");

        DeductRate.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        YearlySalaryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearlySalaryLabel.setText("Yearly Salary");

        YearlySalary.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaleFemaleGroup.add(FemaleButton);
        FemaleButton.setText("Female");

        MaleFemaleGroup.add(MaleButton);
        MaleButton.setText("Male");

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FemaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(YearlySalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FemaleButton)
                    .addComponent(MaleButton))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WorkLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WorkLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeductRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YearlySalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(YearlySalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>                        

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        try {
            FTE fte = new FTE();
            fte.empNum = Integer.parseInt(EmployeeNumber.getText());
            if (table.getFromTable(fte.empNum) != null) {
                JOptionPane.showMessageDialog(null, "Employee already exists!", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }            
            fte.firstName = FirstName.getText().strip();
            fte.lastName = LastName.getText().strip();
            if (MaleButton.isSelected()) {
                fte.gender = "Male";
            }
            if (FemaleButton.isSelected()) {
                fte.gender = "Female";
            }
            fte.workLoc = WorkLocation.getText().strip();
            fte.deductRate = Double.parseDouble(DeductRate.getText());
            fte.yearlySalary = Double.parseDouble(YearlySalary.getText());

            if (fte.firstName.equals("") || fte.lastName.equals("") || fte.workLoc.equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid employee input", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }       
            
            if (fte.deductRate < 0 || fte.deductRate > 1) {
                JOptionPane.showMessageDialog(null, "Deduct rate must be between 0 and 1 (inclusive)", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if (fte.yearlySalary < 0) {
                JOptionPane.showMessageDialog(null, "Yearly salary must be greater than 0", "", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            table.addToTable(fte);

            try {
                FileWriter myWriter = new FileWriter("employeeInfo.txt");
                for (int i = 0; i < table.buckets.length; i++) {
                    if (table.buckets[i].isEmpty()) {
                        continue; 
                    }
                    else {
                        for (int j = 0; j < table.buckets[i].size(); j++) {
                            if (table.buckets[i].get(j) instanceof PTE) {
                                PTE partTime = (PTE) table.buckets[i].get(j);
                                myWriter.write("PTE@@@\n");
                                myWriter.write(partTime.empNum + "\n");
                                myWriter.write(partTime.firstName + "\n");
                                myWriter.write(partTime.lastName + "\n");
                                myWriter.write(partTime.gender + "\n");
                                myWriter.write(partTime.workLoc + "\n");
                                myWriter.write(partTime.deductRate + "\n");
                                myWriter.write(partTime.hourlyWage + "\n");
                                myWriter.write(partTime.hoursPerWeek + "\n");
                                myWriter.write(partTime.weeksPerYear + "\n");
                            }
                            else if (table.buckets[i].get(j) instanceof FTE) {
                                FTE fullTime = (FTE) table.buckets[i].get(j);
                                myWriter.write("FTE@@@\n");
                                myWriter.write(fullTime.empNum + "\n");
                                myWriter.write(fullTime.firstName + "\n");
                                myWriter.write(fullTime.lastName + "\n");
                                myWriter.write(fullTime.gender + "\n");
                                myWriter.write(fullTime.workLoc + "\n");
                                myWriter.write(fullTime.deductRate + "\n");
                                myWriter.write(fullTime.yearlySalary + "\n");
                            }
                        }
                    }
                }
                System.out.println("Successfully wrote to the file.");
                myWriter.close();
            } catch (IOException e) {
              System.out.println("An error occurred.");
              e.printStackTrace();
            }                        
            
            homepageFrame.setVisible(true);
            System.out.println("added FTE!");

            this.dispose();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid employee input", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }                                            

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        cancelFrame.setVisible(true);
        
        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTEInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTEInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DeductRate;
    private javax.swing.JLabel DeductRateLabel;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JTextField FirstName;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JTextField LastName;
    private javax.swing.JLabel LastNameLable;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.ButtonGroup MaleFemaleGroup;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitCancelPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField WorkLocation;
    private javax.swing.JLabel WorkLocationLabel;
    private javax.swing.JTextField YearlySalary;
    private javax.swing.JLabel YearlySalaryLabel;
    // End of variables declaration                   
}
