/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileNotFoundException;  // Import this class to handle errors
import java.util.Scanner; // Import the Scanner class to read text files

/**
 *
 * @author snyou
 */
public class Homepage extends javax.swing.JFrame {

    public MyHashTable table;
    /**
     * Creates new form Homepage
     */
    public Homepage() {
        table = new MyHashTable(10);
        
        try {
            File myObj = new File("employeeInfo.txt");
            Scanner myReader = new Scanner(myObj);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                if (data.equals("PTE@@@")) {
                    PTE pte = new PTE();
                    pte.empNum = Integer.parseInt(myReader.nextLine());
                    pte.firstName = myReader.nextLine();
                    pte.lastName = myReader.nextLine();
                    pte.gender = myReader.nextLine();
                    pte.workLoc = myReader.nextLine();
                    pte.deductRate = Double.parseDouble(myReader.nextLine());
                    pte.hourlyWage = Double.parseDouble(myReader.nextLine());
                    pte.hoursPerWeek = Double.parseDouble(myReader.nextLine());
                    pte.weeksPerYear = Double.parseDouble(myReader.nextLine());

                    table.addToTable(pte);
                }
                else if (data.equals("FTE@@@")) {
                    FTE fte = new FTE();
                    fte.empNum = Integer.parseInt(myReader.nextLine());
                    fte.firstName = myReader.nextLine();
                    fte.lastName = myReader.nextLine();
                    fte.gender = myReader.nextLine();
                    fte.workLoc = myReader.nextLine();
                    fte.deductRate = Double.parseDouble(myReader.nextLine());
                    fte.yearlySalary = Double.parseDouble(myReader.nextLine());
                    
                    table.addToTable(fte);
                }
            }
            myReader.close();
            System.out.println("Employees added to hash table.");
        }
        catch (FileNotFoundException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        initComponents();        
    }
    
    public MyHashTable getTheHT() {
        return table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Title = new javax.swing.JLabel();
        ButtonHolder = new javax.swing.JPanel();
        AddEmployeeButton = new javax.swing.JButton();
        RemoveEmployeeButton = new javax.swing.JButton();
        SearchEmployeeButton = new javax.swing.JButton();
        EditEmployeeButton = new javax.swing.JButton();
        DisplayEmployeesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Employee Management System");

        AddEmployeeButton.setText("Add Employee");
        AddEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeButtonActionPerformed(evt);
            }
        });

        RemoveEmployeeButton.setText("Remove Employee");
        RemoveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeButtonActionPerformed(evt);
            }
        });

        SearchEmployeeButton.setText("Search Employee");
        SearchEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchEmployeeButtonActionPerformed(evt);
            }
        });

        EditEmployeeButton.setText("Edit Employee");
        EditEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditEmployeeButtonActionPerformed(evt);
            }
        });

        DisplayEmployeesButton.setText("Display All Employees");
        DisplayEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayEmployeesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonHolderLayout = new javax.swing.GroupLayout(ButtonHolder);
        ButtonHolder.setLayout(ButtonHolderLayout);
        ButtonHolderLayout.setHorizontalGroup(
            ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonHolderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisplayEmployeesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ButtonHolderLayout.createSequentialGroup()
                        .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(RemoveEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonHolderLayout.createSequentialGroup()
                        .addComponent(SearchEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(EditEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        ButtonHolderLayout.setVerticalGroup(
            ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonHolderLayout.createSequentialGroup()
                .addGroup(ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(ButtonHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(DisplayEmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonHolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void SearchEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        SearchEmployee searchEmployeeFrame = new SearchEmployee();
        searchEmployeeFrame.setVisible(true);
        searchEmployeeFrame.setMainHT(table);
        searchEmployeeFrame.setHomepage(this);
        
        this.setVisible(false);
    }                                                    

    private void EditEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        EditEmployeeSearch editEmployeeFrame = new EditEmployeeSearch();
        editEmployeeFrame.setVisible(true);
        editEmployeeFrame.setMainHT(table);
        editEmployeeFrame.setHomepage(this);
        
        this.setVisible(false);
    }                                                  

    private void AddEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        PTE_or_FTE addEmployeeFrame = new PTE_or_FTE();
        addEmployeeFrame.setVisible(true);
        addEmployeeFrame.setMainHT(table);
        addEmployeeFrame.setHomepage(this);
        
        this.setVisible(false);
    }                                                 

    private void RemoveEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        RemoveEmployee removeEmployeeFrame = new RemoveEmployee();
        removeEmployeeFrame.setVisible(true);
        removeEmployeeFrame.setMainHT(table);
        removeEmployeeFrame.setHomepage(this);
        
        this.setVisible(false);
    }                                                    

    private void DisplayEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        DisplayEmployees displayEmployeesFrame = new DisplayEmployees();
        displayEmployeesFrame.setVisible(true);
        displayEmployeesFrame.setMainHT(table);
        displayEmployeesFrame.setHomepage(this);
        
        this.setVisible(false);
    }                                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddEmployeeButton;
    private javax.swing.JPanel ButtonHolder;
    private javax.swing.JButton DisplayEmployeesButton;
    private javax.swing.JButton EditEmployeeButton;
    private javax.swing.JButton RemoveEmployeeButton;
    private javax.swing.JButton SearchEmployeeButton;
    private javax.swing.JLabel Title;
    // End of variables declaration                   
}
