/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ems;
import javax.swing.JOptionPane;

/**
 *
 * @author snyou
 */
public class SearchEmployee extends javax.swing.JFrame {

    private MyHashTable table;
    private Homepage homepageFrame;
    /**
     * Creates new form SearchEmployee
     */
    public SearchEmployee() {
        initComponents();
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        table = refvalForHT;
    }

    public void setHomepage(Homepage refvalForHP) {
        homepageFrame = refvalForHP;
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputPanel = new javax.swing.JPanel();
        EmployeeNumberLabel = new javax.swing.JLabel();
        EmployeeNumber = new javax.swing.JTextField();
        SubmitCancelPanel = new javax.swing.JPanel();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        EmployeeNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmployeeNumberLabel.setText("Employee Number");
        InputPanel.add(EmployeeNumberLabel);

        EmployeeNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InputPanel.add(EmployeeNumber);

        SubmitCancelPanel.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(SubmitButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        SubmitCancelPanel.add(CancelButton);

        Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Search For An Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(SubmitCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        try {
            int empNum = Integer.parseInt(EmployeeNumber.getText());
            
            EmployeeInfo refNumber = table.getFromTable(empNum);

                if (refNumber instanceof PTE) {
                    DisplayPTE displayPTEFrame = new DisplayPTE();
                    displayPTEFrame.setVisible(true);
                    displayPTEFrame.setHomepage(homepageFrame);
                    displayPTEFrame.setRefVal(refNumber);

                    this.dispose();
                }
                else if (refNumber instanceof FTE) {
                    DisplayFTE displayFTEFrame = new DisplayFTE();
                    displayFTEFrame.setVisible(true);
                    displayFTEFrame.setHomepage(homepageFrame);
                    displayFTEFrame.setRefVal(refNumber);

                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Employee does not exist", "", JOptionPane.INFORMATION_MESSAGE);
                }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Employee Input", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        homepageFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField EmployeeNumber;
    private javax.swing.JLabel EmployeeNumberLabel;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JPanel SubmitCancelPanel;
    private javax.swing.JLabel Title;
    // End of variables declaration//GEN-END:variables
}
